# ************************************************************
# Sequel Pro SQL dump
# Version 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: 127.0.0.1 (MySQL 5.5.34)
# Database: blog
# Generation Time: 2015-01-25 14:30:49 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table articles
# ------------------------------------------------------------

DROP TABLE IF EXISTS `articles`;

CREATE TABLE `articles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `author` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `contents` text COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

LOCK TABLES `articles` WRITE;
/*!40000 ALTER TABLE `articles` DISABLE KEYS */;

INSERT INTO `articles` (`id`, `title`, `slug`, `author`, `description`, `contents`, `created_at`, `updated_at`)
VALUES
	(1,'Est et consectetur expedita reiciendis ut eos consequuntur omnis placeat odit.','est-et-consectetur-expedita-reiciendis-ut-eos-consequuntur-omnis-placeat-odit.','Esperanza Flatley','Aut a qui eos officia totam distinctio iure. Temporibus excepturi quasi aliquam provident. Voluptas aut doloribus explicabo ad sed non odio.','<p>King, rubbing his hands; \'so now let the jury--\' \'If any one left alive!\' She was looking about for them, but they began running when they arrived, with a knife, it usually bleeds; and she tried hard to whistle to it; but she could for sneezing. There was a paper.</p><p>I can find out the words: \'Where\'s the other queer noises, would change (she knew) to the game, the Queen till she shook the house, \"Let us both go to law: I will prosecute YOU.--Come, I\'ll take no denial; We must have got into the book her sister was reading, but it all is! I\'ll try if I might venture to ask them what the name of the same thing as \"I get what I eat\" is the same thing as a partner!\' cried the Mock Turtle to sing you a present of everything I\'ve said as yet.\' \'A cheap sort of lullaby to it as you go.</p><p>PRECIOUS nose\'; as an unusually large saucepan flew close by her. There was a table set out under a tree a few yards off. The Cat only grinned a little worried. \'Just about as it didn\'t much matter which way she put her hand in her head, she tried the little door, had vanished completely. Very soon the Rabbit noticed Alice, as the hall was very deep, or she fell very slowly, for she had but to open her mouth; but she did not feel encouraged to ask the question?\' said the others. \'Are their heads down! I am to see what this bottle does. I do it again and again.\' \'You are old,\' said the White Rabbit.</p>','2015-01-25 11:21:37','2015-01-25 11:21:37'),
	(2,'Dicta a fugit totam quidem deleniti et consequatur consequuntur nam ut.','dicta-a-fugit-totam-quidem-deleniti-et-consequatur-consequuntur-nam-ut.','Isaac Welch DVM','Ratione eligendi quisquam praesentium. Laborum doloremque sint maiores mollitia consequatur dolor dolore rerum. Quo eaque et non commodi fugiat. Aspernatur voluptas iure delectus.','<p>Bill\'s place for a good deal: this fireplace is narrow, to be ashamed of yourself,\' said Alice, as she stood watching them, and then nodded. \'It\'s no use in talking to herself, as well to say a word, but slowly followed her back to the King, who had got its head to hide a smile: some of them even when they arrived, with a shiver. \'I beg your acceptance of this ointment--one shilling the box-- Allow me to introduce some other subject of conversation. While she was now the right size, that it is!\' As she said to herself; \'I should like to be no use now,\' thought poor Alice, who was gently brushing away some dead leaves that had fallen into the earth. Let me think: was I the same year for such a puzzled expression that she was quite silent for a minute, trying to explain the mistake it had no idea how confusing it is almost certain to disagree with you, sooner or later. However, this bottle was a general clapping of hands at this: it was certainly.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(3,'Voluptatem quas molestiae ullam soluta pariatur quis quas odit neque.','voluptatem-quas-molestiae-ullam-soluta-pariatur-quis-quas-odit-neque.','Eva Nikolaus','Rerum quidem inventore maxime est voluptatem. Natus iusto est odit pariatur in officia beatae. Adipisci consequatur vel quasi occaecati impedit perspiciatis consequatur.','<p>Edwin and Morcar, the earls of Mercia and Northumbria--\"\' \'Ugh!\' said the Pigeon; \'but I must be off, and that if something wasn\'t done about it while the Dodo had paused as if a fish came to the Classics master, though. He was an old crab, HE was.\' \'I never went to school every day--\' \'I\'VE been to her, one on each side, and opened their eyes and mouths so VERY tired of being all alone here!\' As she said these words her foot slipped, and in another moment down went Alice like the three were all in bed!\' On various pretexts they all moved off, and that you weren\'t to talk to.\' \'How are you getting on?\' said Alice, seriously, \'I\'ll.</p><p>Alice crouched down among the bright flower-beds and the baby--the fire-irons came first; then followed a shower of saucepans, plates, and dishes. The Duchess took her choice, and was in livery: otherwise, judging by his garden.\"\' Alice did not at all comfortable, and it said in a trembling voice to a mouse, That he met in the morning, just time to see if there are, nobody attends to them--and you\'ve no idea what to say \"HOW DOTH THE LITTLE BUSY BEE,\" but it was as much right,\' said the Eaglet. \'I don\'t know what to do that,\' said the Gryphon, the squeaking of the sea.\' \'I couldn\'t afford to learn it.\' said the sage, as he shook both his shoes off. \'Give your evidence,\' said the Duchess; \'and most of \'em do.\' \'I don\'t believe there\'s an atom of meaning in them, after all. \"--SAID I COULD NOT SWIM--\" you can\'t take more.\' \'You mean you can\'t help it,\' said Alice to herself, \'to be going messages for a minute, trying to touch her. \'Poor little thing!\' It did so indeed, and much sooner than she had never seen such a subject! Our family always HATED cats: nasty, low, vulgar things! Don\'t let me help to undo it!\' \'I shall sit here,\' he said,.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(4,'Itaque culpa eos sed temporibus ullam.','itaque-culpa-eos-sed-temporibus-ullam.','Dr. Erik Frami IV','Molestiae doloribus qui architecto quia et dolorem sint. Nemo explicabo sed architecto sit sunt. Dolorem voluptas rem sit itaque amet qui.','<p>Alice had not gone much farther before she had finished, her sister sat still just as she could see her after the candle is like after the rest of the house, quite forgetting in the night? Let me see: that would happen: \'\"Miss Alice! Come here directly, and get ready to sink into the sea, some children digging in the middle, wondering how she would get up and beg for its dinner, and all dripping wet, cross, and uncomfortable. The moment Alice felt so desperate that she was considering in her French lesson-book. The Mouse only growled in reply. \'Please come back and see that the poor little juror (it was Bill, the Lizard) could not think of anything to put the Dormouse followed him: the March Hare said--\' \'I didn\'t!\' the March Hare will be the best cat in the morning, just time to wash the things between whiles.\' \'Then you shouldn\'t talk,\' said the voice. \'Fetch me my gloves this moment!\' Then came a little irritated at the stick, and tumbled head over heels in its sleep \'Twinkle, twinkle, twinkle, twinkle--\' and went on in a minute. Alice began telling them her adventures from the time they had.</p><p>Said his father; \'don\'t give yourself airs! Do you think, at your age, it is right?\' \'In my youth,\' said his father, \'I took to the Hatter. He came in sight of the words a little, half expecting to see you any more!\' And here poor Alice began in a frightened tone. \'The Queen of Hearts were seated on their slates, and she went on all the while, and fighting for the garden!\' and she trembled till she too began dreaming after a few yards off. The Cat only grinned when it saw Alice. It looked good-natured, she thought: still.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(5,'A aliquam et ut quo eveniet quidem.','a-aliquam-et-ut-quo-eveniet-quidem.','Dr. Mona Goodwin MD','Alias accusantium vel laboriosam autem fuga ea dicta. Omnis asperiores cum consectetur nihil laboriosam necessitatibus. Et enim ut delectus dicta laudantium.','<p>Hatter. Alice felt dreadfully puzzled. The Hatter\'s remark seemed to have wondered at this, that she began shrinking directly. As soon as she could not help bursting out laughing: and when she had found the fan and gloves, and, as they used to say.\' \'So he did, so he with his whiskers!\' For some minutes the whole pack rose up into the loveliest garden you ever eat a bat?\' when suddenly, thump! thump! down she came upon a little girl,\' said Alice, \'how am I to do it.\' (And, as you can--\' \'Swim after them!\' screamed the Queen. \'Never!\' said the Dodo solemnly, rising to its children, \'Come away, my dears! It\'s high time you were never even spoke to Time!\' \'Perhaps not,\'.</p><p>Alice remarked. \'Right, as usual,\' said the Gryphon went on. \'Or would you tell me,\' said Alice, \'but I haven\'t had a bone in his throat,\' said the Hatter. \'You MUST remember,\' remarked the King, going up to the fifth bend, I think?\' \'I had NOT!\' cried the Gryphon, and the m--\' But here, to Alice\'s great surprise, the Duchess\'s cook. She carried the pepper-box in her pocket) till she shook the house, and wondering whether she ought not to lie down upon her: she gave her answer. \'They\'re done with blacking, I believe.\' \'Boots and shoes under the sea--\' (\'I haven\'t,\' said Alice)--\'and perhaps you were never even introduced to a day-school, too,\' said Alice; \'it\'s laid for a dunce? Go on!\' \'I\'m a poor man, your Majesty,\' the Hatter began, in a helpless sort of.</p><p>I did: there\'s no harm in trying.\' So she began again: \'Ou est ma chatte?\' which was a body to cut it off from: that he shook both his shoes off. \'Give your evidence,\' said the Hatter. \'You MUST remember,\' remarked the King, rubbing his hands; \'so now let the jury--\' \'If any one left alive!\' She was walking hand in her French lesson-book. The Mouse gave a sudden leap out of sight, he said to live. \'I\'ve seen hatters before,\' she.</p><p>Alice caught the baby at her feet as the Lory positively refused to tell me who YOU are, first.\' \'Why?\' said the Queen, turning purple. \'I won\'t!\' said Alice. \'You must be,\' said the Gryphon. \'The reason is,\' said the Mock Turtle would be QUITE as much as she could not be denied, so she went hunting about, and crept a little startled by seeing the Cheshire Cat: now I shall be punished for it now, I suppose, by being.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(6,'Neque ipsa non laborum.','neque-ipsa-non-laborum.','Prof. Garnett Heathcote PhD','Autem soluta laudantium tenetur. Sed tempora deserunt est autem.','<p>Caterpillar; and it was the Duchess\'s voice died away, even in the morning, just time to see it trying in a great thistle, to keep back the wandering hair that curled all over crumbs.\' \'You\'re wrong about the same year for such a pleasant temper, and thought to herself. \'Of the mushroom,\' said the Gryphon, \'she wants for to know what a wonderful dream it had come to.</p><p>After a while she ran, as well look and see that the reason of that?\' \'In my youth,\' Father William replied to his son, \'I feared it might belong to one of the sort,\' said the Cat again, sitting on the shingle--will you come to the Knave of Hearts, carrying the King\'s crown on a three-legged stool in the house down!\' said the King. \'It began with the other: the Duchess said in an impatient tone: \'explanations take such a thing as \"I sleep when I get it home?\' when it saw Alice. It looked good-natured, she thought: still it was indeed: she was now only ten inches high, and her face brightened up again.) \'Please your Majesty,\' said Alice to herself. \'I dare say you\'re wondering why I don\'t think,\' Alice went on again:-- \'I didn\'t know how to get hold of this ointment--one shilling the box-- Allow me to sell you a.</p><p>Which shall sing?\' \'Oh, YOU sing,\' said the Queen to-day?\' \'I should think you\'ll feel it a minute or two, they began solemnly dancing round and round Alice, every now and then, \'we went to the conclusion that it might injure the brain; But, now that I\'m doubtful about the crumbs,\' said the Queen. \'Sentence first--verdict afterwards.\' \'Stuff and nonsense!\' said Alice to herself, and once she remembered that she wanted to send the hedgehog to, and, as she went on, \'--likely to win, that it\'s hardly worth while finishing the game.\' The Queen smiled and passed on. \'Who ARE you talking to?\' said one of these cakes,\' she thought, \'till its ears have come, or at least one of them can explain it,\' said the Hatter: \'but you could draw treacle out of the water, and seemed to think this a very melancholy voice. \'Repeat, \"YOU ARE OLD, FATHER WILLIAM,\"\' said the King, the Queen, \'and he shall tell you my history, and you\'ll understand why it is almost certain to disagree with you, sooner or later. However, this bottle was a little shriek and a Canary called out as loud as she was getting.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(7,'Repellendus earum maiores aliquam incidunt adipisci quos aperiam est magnam occaecati sed.','repellendus-earum-maiores-aliquam-incidunt-adipisci-quos-aperiam-est-magnam-occaecati-sed.','Dr. Nadia Rosenbaum MD','Adipisci minima consequuntur rerum illum voluptas accusamus ab laboriosam. Est sed sunt rerum perspiciatis praesentium molestias. Et est porro facere expedita voluptatum.','<p>King. \'When did you call it purring, not growling,\' said Alice. \'You must be,\' said the Duchess; \'I never heard before, \'Sure then I\'m here! Digging for apples, indeed!\' said the Mock Turtle. \'Very much indeed,\' said Alice. \'Why?\' \'IT DOES THE BOOTS AND SHOES.\' the Gryphon replied very readily: \'but that\'s because it stays the same solemn tone, only changing the order of the treat. When the pie was all very well as I used--and I don\'t think,\' Alice went on, \'if you don\'t explain it is I hate cats and dogs.\' It was high time to avoid shrinking away altogether. \'That WAS a curious feeling!\' said.</p><p>I see\"!\' \'You might just as well as I tell you, you coward!\' and at once took up the little door was shut again, and she felt that there was the White Rabbit read:-- \'They told me you had been would have called him Tortoise because he taught us,\' said the King. \'Shan\'t,\' said the King, with an important air, \'are you all ready? This is the capital of Rome,.</p><p>Caterpillar took the hookah into its face was quite pleased to have no sort of lullaby to it in large letters. It was all ridges and furrows; the balls were live hedgehogs, the mallets live flamingoes, and the other guinea-pig cheered, and was in the middle, being held up by a very poor speaker,\' said the Hatter: \'but you could only hear whispers now and then, and holding it to annoy, Because he knows it teases.\' CHORUS. (In which the March Hare was said to Alice, that she hardly knew what she did, she picked up a little pattering of feet on the whole party at once took up the other, saying, in a tone of great curiosity. \'Soles and eels, of course,\' the Gryphon interrupted in a melancholy air, and, after waiting till she fancied she heard was a dispute going on within--a constant howling and sneezing, and every now and then she.</p><p>Conqueror.\' (For, with all her wonderful Adventures, till she heard a little before she got up, and began talking again. \'Dinah\'ll miss me very much pleased at having found out a race-course, in a tone of great curiosity. \'Soles and eels, of course,\' he said to herself, \'because of his pocket, and pulled out a new.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(8,'Consectetur sed laboriosam perferendis facilis ratione.','consectetur-sed-laboriosam-perferendis-facilis-ratione.','Nat Bernier','Sequi harum adipisci recusandae dolore est. Dolores eum dolorem et. Mollitia quisquam est et officia aut.','<p>She pitied him deeply. \'What is his sorrow?\' she asked the Mock Turtle, suddenly dropping his voice; and Alice guessed in a rather offended tone, and added \'It isn\'t a bird,\' Alice remarked. \'Right, as usual,\' said the Caterpillar. This was not quite know what to do so. \'Shall we try another figure of the e--e--evening, Beautiful, beautiful Soup!\' CHAPTER XI. Who Stole the Tarts? The King turned pale, and shut his eyes.--\'Tell her about the reason so many lessons to learn! Oh, I shouldn\'t like THAT!\' \'Oh, you foolish Alice!\' she answered herself. \'How can you learn lessons in the act of crawling away: besides all.</p><p>Alice said; but was dreadfully puzzled by the hedge!\' then silence, and then treading on my tail. See how eagerly the lobsters to the door, she found it made Alice quite jumped; but she was surprised to see what would be quite absurd for her to wink with one of them can explain it,\' said Alice. \'Then it doesn\'t matter much,\' thought Alice, \'it\'ll never do to hold it. As soon as she was now about two feet high, and she soon made out the answer to.</p><p>Queen,\' and she had someone to listen to her. The Cat seemed to quiver all over with diamonds, and walked a little glass box that was trickling down his face, as long as I get it home?\' when it grunted again, and looking anxiously about as much as she went on again: \'Twenty-four hours, I THINK; or is it directed to?\' said the Hatter: \'as the things I used to it as you can--\' \'Swim after them!\' screamed the Gryphon. \'They can\'t have anything to put everything upon Bill! I wouldn\'t say anything about it, so she took courage, and went down on her spectacles, and began smoking again. This time there could be no use going back to the Mock Turtle. So she went on, \'if you don\'t know of any one; so, when the race was over. However, when they liked, and left foot, so as to bring tears into.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(9,'Perferendis dolore eum dolor modi voluptas repellendus praesentium.','perferendis-dolore-eum-dolor-modi-voluptas-repellendus-praesentium.','Nikko Volkman','Sed et itaque quidem esse unde pariatur. Est perferendis recusandae molestiae officiis omnis enim voluptas. Quo veniam harum qui aut.','<p>Gryphon, \'you first form into a chrysalis--you will some day, you know--and then after that into a cucumber-frame, or something of the goldfish kept running in her pocket) till she too began dreaming after a minute or two, it was not here before,\' said Alice,) and round Alice, every now and then; such as, that a moment\'s pause. The only things in the house, quite forgetting in the schoolroom, and though this was her turn or not. \'Oh, PLEASE mind what you\'re doing!\' cried Alice, with a bound into the sky. Alice went on all the things get used up.\' \'But what happens when you come to the fifth bend, I think?\' he said to Alice. \'Nothing,\' said Alice. \'Come, let\'s try Geography. London is the capital of Rome, and Rome--no, THAT\'S all wrong, I\'m certain! I must go by the English, who wanted leaders, and had just begun to think that very few little girls of her hedgehog. The hedgehog was engaged in a deep, hollow tone: \'sit down, both of you, and don\'t speak a word till I\'ve finished.\' So they couldn\'t get them out with trying, the poor child, \'for I can\'t be civil, you\'d better finish the story for.</p><p>I\'ll tell him--it was for bringing the cook tulip-roots instead of the ground--and I should frighten them out of its voice. \'Back to land again, and looking anxiously about her. \'Oh, do let me hear the rattle of the miserable Mock Turtle. \'She can\'t explain MYSELF, I\'m afraid, sir\' said Alice, rather alarmed at the jury-box, or they would die. \'The trial cannot proceed,\' said the March Hare. \'It was the Hatter. This piece of it had no pictures or conversations?\' So she set off at once took up the little passage: and THEN--she found herself in Wonderland, though she felt certain it must be removed,\' said the Footman, and began whistling. \'Oh, there\'s no room at all anxious to have changed since her swim in the kitchen. \'When I\'M a Duchess,\' she said this, she noticed a curious dream, dear, certainly: but now run in to your little boy, And beat him.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38'),
	(10,'Quod quod sint cum in et libero voluptatum voluptatem error nobis.','quod-quod-sint-cum-in-et-libero-voluptatum-voluptatem-error-nobis.','Aiden Dickens','Ut dolorem tempora velit dignissimos reprehenderit quas distinctio. Qui temporibus aspernatur dolorum qui sint. Omnis saepe dicta amet ut id. Quasi voluptas doloribus est earum ex.','<p>She felt very glad that it had no idea how confusing it is all the unjust things--\' when his eye chanced to fall a long sleep you\'ve had!\' \'Oh, I\'ve had such a capital one for catching mice you can\'t take LESS,\' said the Mock Turtle. \'Seals, turtles, salmon, and so on; then, when you\'ve cleared all the players, except the King, rubbing his hands; \'so now let the jury--\' \'If any one of them say, \'Look out now, Five! Don\'t go splashing paint over me like that!\' But she waited for a minute or two, and the cool fountains. CHAPTER VIII. The Queen\'s argument was, that you had been wandering, when a cry of \'The trial\'s beginning!\' was heard in the direction in which case it would like the look of the country is, you see, Alice had been running half an hour or so, and were resting in the other. \'I beg pardon, your Majesty,\' he began. \'You\'re a very difficult question. However, at last came a little house in it about four feet high. \'I wish you could manage it?) \'And what an ignorant little girl or a worm. The question is, what?\' The great question is, what did the.</p><p>Caterpillar. \'Well, I\'ve tried to get us dry would be grand, certainly,\' said Alice, \'and why it is you hate--C and D,\' she added aloud. \'Do you mean that you think you could see this, as she could. The next witness was the King; and as the question was evidently meant for her. \'Yes!\' shouted Alice. \'Come on, then!\' roared the Queen, \'Really, my dear, and that he had taken advantage of the cupboards as she could even make out what it might belong to one of the trees as well as pigs, and was a queer-shaped little creature, and held it out loud. \'Thinking again?\' the Duchess replied, in a game.</p>','2015-01-25 11:21:38','2015-01-25 11:21:38');

/*!40000 ALTER TABLE `articles` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table comments
# ------------------------------------------------------------

DROP TABLE IF EXISTS `comments`;

CREATE TABLE `comments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `article_id` int(11) NOT NULL,
  `author` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `contents` text COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

LOCK TABLES `comments` WRITE;
/*!40000 ALTER TABLE `comments` DISABLE KEYS */;

INSERT INTO `comments` (`id`, `article_id`, `author`, `contents`, `created_at`, `updated_at`)
VALUES
	(1,8,'bschowalter','Quasi et voluptatum blanditiis magnam. Tempore nihil libero temporibus quia.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(2,3,'johnpaul.shanahan','Reiciendis natus sunt officia quibusdam pariatur ratione aliquam. Voluptatum impedit exercitationem omnis quibusdam. Ullam aut neque suscipit minus.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(3,4,'','Quia minima quo qui culpa odio fugiat autem. Harum iste et consequuntur est molestiae. Sed suscipit id repellat. Ullam velit quae laboriosam atque asperiores molestias.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(4,1,'harvey.hildegard','Ratione distinctio sapiente possimus cupiditate ab facilis aut. Aut iusto quia iusto ut velit sint. Voluptatibus vel itaque non ut quo officiis officia.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(5,4,'murazik.agnes','Magni aut dolor fuga illum quisquam est porro. Architecto sed est est. Minima impedit quae esse.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(6,2,'donny.kovacek','Ratione reprehenderit vero dignissimos esse. Occaecati provident nemo nisi. Et ea molestiae quae sequi eum qui.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(7,9,'hmann','Maiores beatae qui aspernatur eaque. Eum sit quibusdam vero error qui sit eligendi. Hic est assumenda et deleniti reiciendis et. Et non occaecati exercitationem maiores maxime iure.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(8,4,'hilario.stokes','Rerum porro corrupti vel. Ipsum corrupti quod aperiam quibusdam culpa accusamus adipisci suscipit. Quia sequi dolore cupiditate. Assumenda aspernatur molestiae odit odio.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(9,4,'kristian17','Praesentium qui in aspernatur voluptates. Ut voluptas maxime ipsam dolorem. Error necessitatibus doloremque deserunt ab assumenda necessitatibus.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(10,1,'kayla.kihn','Aperiam quam aliquam cumque omnis nemo. Repellat sit ratione hic tempora ex et sequi. Ut ducimus earum totam possimus. Sed quae unde voluptate omnis.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(11,5,'reba70','Fuga deleniti non consequatur amet ratione officia laboriosam neque. Quia earum aliquam quod aut. Dolorem aut magnam et ipsum. Molestiae deserunt et veniam earum.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(12,3,'danika24','Molestias fugiat temporibus minus neque. Eos veritatis corrupti in consequatur nihil maiores. Fugiat non sapiente aut vel et ut. Voluptatem sed aperiam nobis laudantium cumque molestiae.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(13,4,'zsmith','Itaque et architecto est iste sed molestias. Facere quod enim magnam quod nostrum quod rem ducimus. Quo dolore asperiores nemo rem qui porro ipsam. Laboriosam fuga dolorem voluptas unde id rem enim.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(14,7,'koelpin.virginia','Ut voluptas dolorem est laborum facilis ut a. Vel quisquam optio dignissimos odio error. Fuga atque vel doloremque.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(15,10,'nadia99','Voluptatem voluptate natus rem unde ut non eveniet. Et inventore nobis ad cumque iusto quo quia eos. Qui esse in perspiciatis odio ut possimus. Iure quia qui quaerat doloribus modi et.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(16,3,'stephen30','Et nihil eum asperiores ut nemo a. Sint harum expedita et atque qui rem adipisci enim. Dignissimos perferendis necessitatibus omnis. Ea ea eaque adipisci distinctio.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(17,7,'deion.miller','Eius est consequuntur possimus. Alias incidunt consequatur quia nulla quo et. Aut nihil asperiores soluta et.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(18,1,'abogisich','Maxime quibusdam occaecati fugit. Et corrupti repellat dolores perferendis. Officiis accusamus voluptas magni sapiente qui. Molestiae ad adipisci aut consequuntur consequatur.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(19,1,'wiegand.laurie','Dolor nihil iure odio ex nemo quia. Quibusdam occaecati sed necessitatibus dolorem aperiam. Ab eveniet dolores corporis blanditiis in tempore dolores. Incidunt enim voluptas officia qui vitae dolor.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(20,1,'bertrand.koch','Temporibus non quia ea dicta natus. Est pariatur aut nisi nam sequi. Est in accusamus aspernatur qui at. Hic voluptates voluptatem eos et consequatur delectus eveniet.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(21,5,'hattie51','Vel eligendi consequatur aspernatur fugit sunt dolorem velit. Soluta cumque magni aspernatur. Quo nobis et ipsum molestiae.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(22,9,'tiffany.quitzon','Sapiente non laudantium sit aperiam. Laudantium explicabo repellendus ut incidunt dolorum. Aut architecto vero quo recusandae iure vel.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(23,8,'aliya01','Officiis est iusto ea autem mollitia. Architecto nisi at similique cumque voluptates vel. Pariatur accusamus quas laboriosam dolor.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(24,9,'igleason','Magni incidunt nam voluptas iusto tenetur voluptatem. Cumque corrupti nobis non nulla assumenda. Iste molestiae iusto rerum ut.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(25,5,'ferry.cecile','Sed ut quod ipsa consequuntur reiciendis laborum in. Animi omnis pariatur at quidem aliquid esse. Ad earum fuga rem voluptates.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(26,5,'okon.michelle','Laudantium dicta accusamus et molestiae molestiae quis doloremque. Autem error porro aperiam exercitationem. Sit sint tempore similique et neque.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(27,4,'aida.mcdermott','Non nobis ex nisi. Numquam eveniet eos enim ut. Animi totam ducimus magnam consequatur est. Ut et vel deleniti et consequuntur perferendis fugit.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(28,1,'imcdermott','Dolorem quisquam omnis sit laborum voluptatibus est. Voluptatem voluptates eveniet dolores. Voluptatem aut voluptatem quasi omnis. Ea adipisci explicabo est. Neque nihil est ullam sint.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(29,7,'qdooley','Consequatur itaque corrupti ducimus quisquam consectetur velit. Culpa maxime rerum et illo. Dolore occaecati eius amet.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(30,2,'alba.fisher','Esse earum consequatur praesentium harum. Vitae tenetur quisquam animi voluptatem temporibus molestias nemo. Non sit laboriosam nobis illo praesentium nihil odio.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(31,6,'grant.vinnie','Ex repellat omnis sequi. Temporibus quis ducimus ut dignissimos error sint. Dolore aliquam quisquam neque reiciendis. Mollitia aperiam similique quidem molestiae.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(32,5,'wauer','Et consequatur autem explicabo ut quasi. Possimus nihil dolore unde et. Omnis a eius id et tempora vel.\nQuod sequi consequatur eum. Est optio sint modi sapiente dolorem saepe. Ex unde ea qui.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(33,5,'oleta56','Veritatis voluptas est assumenda sequi magnam. Corporis aut distinctio consequatur blanditiis qui et. Laudantium sit culpa esse quo velit accusantium.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(34,10,'rahul76','Et dolore fugit rem esse facilis assumenda. Qui dignissimos cum aut qui. Omnis similique deleniti suscipit maxime earum.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(35,5,'nicolas.harmony','At ut qui doloribus qui. Totam nobis autem voluptates enim aperiam eos qui voluptas. Explicabo est fuga quo voluptatem sunt qui et quae.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(36,8,'okon.keshaun','Corporis maiores enim voluptas et commodi itaque magni. Iure omnis maiores laudantium.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(37,1,'ccronin','Corporis natus laboriosam explicabo corrupti perspiciatis eveniet numquam. Laudantium architecto perspiciatis harum quaerat deleniti. Facere excepturi ipsam et omnis.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(38,4,'llangosh','Ut natus quasi explicabo id sit nostrum nobis dolor. Suscipit quasi voluptatem et.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(39,1,'pupton','Autem aliquid et magnam iure sint culpa. Eos voluptas rerum rem deserunt voluptas. Praesentium et dolor omnis aut aut autem autem.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(40,5,'meda.beatty','Neque cum excepturi maiores aut. Est omnis quo aperiam veniam exercitationem qui veniam. Ducimus suscipit nemo id soluta temporibus quasi aliquam. Aut blanditiis dolore aut quae animi non incidunt.','2015-01-25 13:12:38','2015-01-25 13:12:38'),
	(47,1,NULL,'Hey,<br />\r\n<br />\r\nThanks for this awesome blog man! &lt;script&gt;alert(\'goo\');&lt;/script&gt;','2015-01-25 14:19:28','2015-01-25 14:19:28'),
	(48,2,NULL,'In your last sentence you are saying &quot;it was certainly.&quot;.<br />\r\n<br />\r\nCould you please elaborate on why it was certainly?','2015-01-25 14:24:52','2015-01-25 14:24:52');

/*!40000 ALTER TABLE `comments` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table migrations
# ------------------------------------------------------------

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `migration` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

LOCK TABLES `migrations` WRITE;
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;

INSERT INTO `migrations` (`migration`, `batch`)
VALUES
	('2015_01_25_095207_create_Articles_table',1),
	('2015_01_25_095834_create_articles_table',2),
	('2015_01_25_111755_create_articles_table',3),
	('2015_01_25_125630_create_comments_table',4),
	('2015_01_25_130316_create_comments_table',5),
	('2015_01_25_131159_create_comments_table',6);

/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
